# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
instance_name: "Ask4.cc"
enable_metrics: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "ultrasecretkey"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
